CC = gcc
CFLAGS = -Wall -I./includes
DEBUG_FLAGS = -DDEBUG

NETWORK_MONITOR_SRC = networkMonitor.c
INTERFACE_MONITOR_SRC = interfaceMonitor.c

NETWORK_MONITOR_OBJ = $(NETWORK_MONITOR_SRC:.c=.o)
INTERFACE_MONITOR_OBJ = $(INTERFACE_MONITOR_SRC:.c=.o)

TARGET_NETWORK_MONITOR = networkMonitor
TARGET_INTERFACE_MONITOR = interfaceMonitor

all: $(TARGET_NETWORK_MONITOR) $(TARGET_INTERFACE_MONITOR)

$(TARGET_NETWORK_MONITOR): $(NETWORK_MONITOR_OBJ)
	$(CC) $(CFLAGS) -o $@ $^

$(TARGET_INTERFACE_MONITOR): $(INTERFACE_MONITOR_OBJ)
	$(CC) $(CFLAGS) -o $@ $^

debug: CFLAGS += $(DEBUG_FLAGS)
debug: all

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@


clean:
	rm -f $(NETWORK_MONITOR_OBJ) $(INTERFACE_MONITOR_OBJ) $(TARGET_NETWORK_MONITOR) $(TARGET_INTERFACE_MONITOR)

run: $(TARGET_NETWORK_MONITOR)
	sudo ./$(TARGET_NETWORK_MONITOR)

.PHONY: all debug clean run_network_monitor 

